spring.application.name=voteapp

spring.datasource.url=jdbc:postgresql://crossover.proxy.rlwy.net:56370/railway
spring.datasource.username=postgres
spring.datasource.password=MVHuDCzeKlqNlmBeDAcrGYJFbbsTUQub
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false